# Generated by Django 3.1.5 on 2021-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('rgType', models.CharField(max_length=10)),
                ('NoPeople', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
